### ISSUE TITLE
Friendly advice 

### ISSUE THREAD

**Issue by Blutornato** [tH3CyberXY/pphud-cheat-csgo#1]
Hello my brother. I saw your great work with my cry this virus was extremely good. Kaspersky didn't got triggered at all even when I run it. You did an outstanding job, and you have insane skills. But unfortunately you are choosing the wrong path. A path that will end in jail. That's why stop this madness before it to late. I don't know if you hate csgo cheaters, or if you need money because you are probably Russian and rubbles don't cost much. Again I lost a year school work because of you. No one deserves that even if he cheats in a silly game. I bet with this python skills you can do better. I hope from the bottom of my heart you will choose a good paths before is to late. I believe you can do greater things in your life. For example if you are Russian you might be able to fix Kaspersky :D. That's all I had to say if you wanna contact me reply here. Good night.

**Comment by tH3CyberXY** [comment]
We do not answer your queries here. Contact us through the forms imposed in the software.

**Comment by tH3CyberXY** [comment]
> Ola meu irmão. Vi seu ótimo trabalho com meu choro esse vírus foi extremamente bom. O Kaspersky não foi acionado mesmo quando eu o executei. Você fez um excelente trabalho e tem habilidades insanas. Mas infelizmente você está escolhendo o caminho errado. Um caminho que terminará na cadeia. É por isso que pare com essa loucura antes que seja tarde. Não sei se você odeia trapaceiros de csgo, ou se precisa de dinheiro porque provavelmente é russo e entulho não custa muito. Mais uma vez, perdi um ano de trabalho escolar por sua causa. Ninguém merece isso, mesmo que trapaceie em um jogo bobo. Aposto que com essas habilidades de python você pode fazer melhor. Espero do fundo do meu coração que você escolha um bom caminho antes que seja tarde demais. Eu acredito que você pode fazer coisas maiores em sua vida. Por exemplo, se você for russo, poderá consertar o Kaspersky :D. Este' s tudo que eu tinha a dizer se você quiser entrar em contato comigo responda aqui. Boa noite.

We don't answer those kinds of questions here. Contact us using the email provided in the software.

**Comment by tH3CyberXY** [comment]
We don't answer those kinds of questions here. Contact us using the email provided in the software.
